# Uncomment this line to define a global platform for your project
platform :ios, '6.1'

source 'https://github.com/CocoaPods/Specs.git'

target 'coffeeApp' do
pod 'Mantle'
pod 'ReactiveCocoa'
pod "AFNetworking", "~> 2.0"
end

target 'coffeeAppTests' do

end

